### ISSUE TITLE
`transient` fails to build

### ISSUE THREAD

**Issue by hvr** [agocorona/transient#3]
See http://matrix.hackage.haskell.org/package/transient and I can't figure out which bounds need to be added to `transient.cabal` other than probably  `base >= 4.6`.

Here's the compile error I'm seeing with GHC 7.6 through 7.10:

```
[1 of 1] Compiling Main             ( move.hs, dist/dist-sandbox-a1f04431/build/move/move-tmp/Main.o )

move.hs:77:34:
    Couldn't match expected type ‘(t, t1)’ with actual type ‘Node’
    Relevant bindings include
      remoteHost :: t (bound at move.hs:77:9)
      remotePort :: t1 (bound at move.hs:77:20)
    In the expression: head $ tail nodes
    In a pattern binding: (remoteHost, remotePort) = head $ tail nodes
    In the expression:
      do { nodes <- logged getNodes;
           logged $ liftIO $ print $ "NODES=" ++ show nodes;
           let (remoteHost, remotePort) = head $ tail nodes;
           examples' remoteHost remotePort }
xcabal: Error: some packages failed to install:
transient-0.1.0.1 failed during the building phase. The exception was:
ExitFailure 1
```

**Comment by agocorona** [comment]
Hi,
Thanks.
I uploaded a new version to Hackage.

2015-08-22 8:33 GMT+02:00 Herbert Valerio Riedel <notifications@github.com>:

> See http://matrix.hackage.haskell.org/package/transient and I can't
> figure out which bounds need to be added to transient.cabal other than
> probably base >= 4.6.
>
> Here's the compile error I'm seeing with GHC 7.6 through 7.10:
>
> [1 of 1] Compiling Main             ( move.hs, dist/dist-sandbox-a1f04431/build/move/move-tmp/Main.o )
>
> move.hs:77:34:
>     Couldn't match expected type ‘(t, t1)’ with actual type ‘Node’
>     Relevant bindings include
>       remoteHost :: t (bound at move.hs:77:9)
>       remotePort :: t1 (bound at move.hs:77:20)
>     In the expression: head $ tail nodes
>     In a pattern binding: (remoteHost, remotePort) = head $ tail nodes
>     In the expression:
>       do { nodes <- logged getNodes;
>            logged $ liftIO $ print $ "NODES=" ++ show nodes;
>            let (remoteHost, remotePort) = head $ tail nodes;
>            examples' remoteHost remotePort }
> xcabal: Error: some packages failed to install:
> transient-0.1.0.1 failed during the building phase. The exception was:
> ExitFailure 1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agocorona/transient/issues/3>.
>



-- 
Alberto.

**Comment by hvr** [comment]
seems better... but it's still broken for GHC 7.0, GHC 7.2 and GHC 7.4:

![snap](https://cloud.githubusercontent.com/assets/285533/9423518/11601b90-48c7-11e5-8692-394fb048c32f.png)

```

[1 of 6] Compiling Transient.Base   ( src/Transient/Base.hs, dist/dist-sandbox-9419efc8/build/Transient/Base.o )

src/Transient/Base.hs:70:20:
    Not in scope: atomicModifyIORef'
    Perhaps you meant `atomicModifyIORef' (imported from Data.IORef)

src/Transient/Base.hs:285:16:
    Not in scope: atomicModifyIORef'
    Perhaps you meant `atomicModifyIORef' (imported from Data.IORef)

src/Transient/Base.hs:286:18:
    Not in scope: atomicModifyIORef'
    Perhaps you meant `atomicModifyIORef' (imported from Data.IORef)

src/Transient/Base.hs:478:24: Not in scope: `forkFinally'
xcabal: Error: some packages failed to install:
transient-0.1.0.2 failed during the building phase. The exception was:
ExitFailure 1
```

Also, was the `transient-0.1.0.1` release completely broken? or is there any chance to get it to compile by using specific versions of the build-dependencies?

**Comment by agocorona** [comment]
Herbert, the failure with the 0.1.0.0 is is because move.hs  does not
compile,, but it is only a test program. it is a matter of removing it from
the cabal file

2015-08-22 12:13 GMT+02:00 Herbert Valerio Riedel <notifications@github.com>
:

> seems better... but it's still broken for GHC 7.0, GHC 7.2 and GHC 7.4:
>
> [image: snap]
> <https://cloud.githubusercontent.com/assets/285533/9423518/11601b90-48c7-11e5-8692-394fb048c32f.png>
>
>
> [1 of 6] Compiling Transient.Base   ( src/Transient/Base.hs, dist/dist-sandbox-9419efc8/build/Transient/Base.o )
>
> src/Transient/Base.hs:70:20:
>     Not in scope: atomicModifyIORef'
>     Perhaps you meant `atomicModifyIORef' (imported from Data.IORef)
>
> src/Transient/Base.hs:285:16:
>     Not in scope: atomicModifyIORef'
>     Perhaps you meant `atomicModifyIORef' (imported from Data.IORef)
>
> src/Transient/Base.hs:286:18:
>     Not in scope: atomicModifyIORef'
>     Perhaps you meant `atomicModifyIORef' (imported from Data.IORef)
>
> src/Transient/Base.hs:478:24: Not in scope: `forkFinally'
> xcabal: Error: some packages failed to install:
> transient-0.1.0.2 failed during the building phase. The exception was:
> ExitFailure 1
>
> Also, was the transient-0.1.0.1 release completely broken? or is there
> any chance to get it to compile by using specific versions of the
> build-dependencies?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agocorona/transient/issues/3#issuecomment-133675003>.
>



-- 
Alberto.

**Comment by agocorona** [comment]
But in the meantime I discovered a bug introduced in the version 1 and
fixed it in the version 2

2015-08-22 16:48 GMT+02:00 Alberto G. Corona <agocorona@gmail.com>:

> Herbert, the failure with the 0.1.0.0 is is because move.hs  does not
> compile,, but it is only a test program. it is a matter of removing it from
> the cabal file
>
> 2015-08-22 12:13 GMT+02:00 Herbert Valerio Riedel <
> notifications@github.com>:
>
>> seems better... but it's still broken for GHC 7.0, GHC 7.2 and GHC 7.4:
>>
>> [image: snap]
>> <https://cloud.githubusercontent.com/assets/285533/9423518/11601b90-48c7-11e5-8692-394fb048c32f.png>
>>
>>
>> [1 of 6] Compiling Transient.Base   ( src/Transient/Base.hs, dist/dist-sandbox-9419efc8/build/Transient/Base.o )
>>
>> src/Transient/Base.hs:70:20:
>>     Not in scope: atomicModifyIORef'
>>     Perhaps you meant `atomicModifyIORef' (imported from Data.IORef)
>>
>> src/Transient/Base.hs:285:16:
>>     Not in scope: atomicModifyIORef'
>>     Perhaps you meant `atomicModifyIORef' (imported from Data.IORef)
>>
>> src/Transient/Base.hs:286:18:
>>     Not in scope: atomicModifyIORef'
>>     Perhaps you meant `atomicModifyIORef' (imported from Data.IORef)
>>
>> src/Transient/Base.hs:478:24: Not in scope: `forkFinally'
>> xcabal: Error: some packages failed to install:
>> transient-0.1.0.2 failed during the building phase. The exception was:
>> ExitFailure 1
>>
>> Also, was the transient-0.1.0.1 release completely broken? or is there
>> any chance to get it to compile by using specific versions of the
>> build-dependencies?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/agocorona/transient/issues/3#issuecomment-133675003>.
>>
>
>
>
> --
> Alberto.
>



-- 
Alberto.

**Comment by agocorona** [comment]
Hope that this new version 0.3 will compile with 7.0 on

2015-08-22 16:52 GMT+02:00 Alberto G. Corona <agocorona@gmail.com>:

> But in the meantime I discovered a bug introduced in the version 1 and
> fixed it in the version 2
>
> 2015-08-22 16:48 GMT+02:00 Alberto G. Corona <agocorona@gmail.com>:
>
>> Herbert, the failure with the 0.1.0.0 is is because move.hs  does not
>> compile,, but it is only a test program. it is a matter of removing it from
>> the cabal file
>>
>> 2015-08-22 12:13 GMT+02:00 Herbert Valerio Riedel <
>> notifications@github.com>:
>>
>>> seems better... but it's still broken for GHC 7.0, GHC 7.2 and GHC 7.4:
>>>
>>> [image: snap]
>>> <https://cloud.githubusercontent.com/assets/285533/9423518/11601b90-48c7-11e5-8692-394fb048c32f.png>
>>>
>>>
>>> [1 of 6] Compiling Transient.Base   ( src/Transient/Base.hs, dist/dist-sandbox-9419efc8/build/Transient/Base.o )
>>>
>>> src/Transient/Base.hs:70:20:
>>>     Not in scope: atomicModifyIORef'
>>>     Perhaps you meant `atomicModifyIORef' (imported from Data.IORef)
>>>
>>> src/Transient/Base.hs:285:16:
>>>     Not in scope: atomicModifyIORef'
>>>     Perhaps you meant `atomicModifyIORef' (imported from Data.IORef)
>>>
>>> src/Transient/Base.hs:286:18:
>>>     Not in scope: atomicModifyIORef'
>>>     Perhaps you meant `atomicModifyIORef' (imported from Data.IORef)
>>>
>>> src/Transient/Base.hs:478:24: Not in scope: `forkFinally'
>>> xcabal: Error: some packages failed to install:
>>> transient-0.1.0.2 failed during the building phase. The exception was:
>>> ExitFailure 1
>>>
>>> Also, was the transient-0.1.0.1 release completely broken? or is there
>>> any chance to get it to compile by using specific versions of the
>>> build-dependencies?
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/agocorona/transient/issues/3#issuecomment-133675003>
>>> .
>>>
>>
>>
>>
>> --
>> Alberto.
>>
>
>
>
> --
> Alberto.
>



-- 
Alberto.
